# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-23 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fechaNacimiento', models.DateField()),
                ('dui', models.CharField(blank=True, max_length=10, null=True)),
                ('solvente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('codigo_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asistencia', models.DateField()),
                ('asistio', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carrera', models.CharField(max_length=20)),
                ('descripcion_carrera', models.CharField(max_length=200)),
                ('cuota_semanal_carrera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_inscripcion_carrera', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo_carrera', models.BooleanField(default=True)),
                ('permitir_inscripcion', models.BooleanField(default=True)),
                ('pensum_mes_carrera', models.IntegerField(default=10)),
                ('pensum_anio_carrera', models.IntegerField(default=2018)),
            ],
        ),
        migrations.CreateModel(
            name='Colegiatura',
            fields=[
                ('codigo_colegiatura', models.AutoField(primary_key=True, serialize=False)),
                ('cuota_semanal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(max_length=100)),
                ('actual_colegiatura', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cursa',
            fields=[
                ('codigo_cursa', models.AutoField(primary_key=True, serialize=False)),
                ('nota_final', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('actual_cursa', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEstado',
            fields=[
                ('codigo_detalle_e', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_detalle_e', models.DateField()),
                ('actual_detalle_e', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('codigo_detalle_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelado', models.BooleanField(default=False)),
                ('cantidad_semanas', models.IntegerField()),
                ('en_cola', models.BooleanField(default=False)),
                ('colegiatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Colegiatura')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePensum',
            fields=[
                ('codigo_detalle_p', models.AutoField(primary_key=True, serialize=False)),
                ('ordinal_materia_cursa', models.IntegerField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('dui', models.CharField(max_length=10)),
                ('isss', models.CharField(max_length=9)),
                ('afp', models.CharField(max_length=12)),
                ('nit', models.CharField(max_length=17)),
                ('tipo', models.CharField(choices=[('Dir', 'Director'), ('Pro', 'Profesor'), ('Sup', 'Supervisor')], default='Pro', max_length=3)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('dui', models.CharField(blank=True, max_length=10, null=True)),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('codigo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('codigo_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota_evaluacion', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('fecha_ingreso_evaluacion', models.DateField(auto_now=True)),
                ('cursa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Cursa')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('codigo_examen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_examen', models.CharField(max_length=100)),
                ('ponderacion_examen', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fecha_realizacion_examen', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('codigo_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('activo_expediente', models.BooleanField(default=True)),
                ('fecha_inicio_exp', models.DateField()),
                ('fecha_proximo_pago_exp', models.DateField()),
                ('pagado_hasta', models.DateField()),
                ('progreso_expediente', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Alumno')),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField()),
                ('alumnosInscritos', models.IntegerField(default=0)),
                ('activo_grupo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('dias_asignados', models.CharField(max_length=40)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cantidad_alumnos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('codigo_ins', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField()),
                ('actual_inscripcion', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Alumno')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=20)),
                ('descripcion_materia', models.CharField(max_length=200)),
                ('activo_materia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('codigo_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('municipio_sucursal', models.CharField(max_length=100)),
                ('direccion_sucursal', models.CharField(max_length=100)),
                ('telefono_sucursal', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=8)),
                ('tipo', models.CharField(max_length=20)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Alumno')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Empleado')),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Encargado')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Horario'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Empleado'),
        ),
        migrations.AddField(
            model_name='examen',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Materia'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Examen'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Sucursal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallepensum',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Materia'),
        ),
        migrations.AddField(
            model_name='detalleestado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Estado'),
        ),
        migrations.AddField(
            model_name='cursa',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Materia'),
        ),
        migrations.AddField(
            model_name='colegiatura',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Expediente'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='sucursal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Sucursal'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_app.Inscripcion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Encargado'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sucursal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.Sucursal'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
